spring:
  application:
    name: easybuy
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easybuy?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/templates/**
  thymeleaf:
    suffix: .html
server:
  port: 6988